In [2]:
# Consider the below code to answer further questions:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [5]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
# to print the data types of both the variables.
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [7]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and
# arra_list.
for element in list_:
    print(type(element))

for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [9]:
# 3.
# Yes, there will be a difference in the data type of the elements present in both the variables, list_ and array_list. The elements in list_ will remain as strings, while the elements in array_list will be converted to integers due to the dtype=int argument.

for element in list_:
    print(type(element))

for element in array_list:
    print(type(element))

# Regarding the new code snippet, num_list is a list of lists, and num_array is a 2D numpy array created from num_list. The elements in both num_list and num_array are integers.

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [11]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape ii) size
print("Shape of num_array:", array_list.shape)
print("Size of num_array:", array_list.size)

Shape of num_array: (5,)
Size of num_array: 5


In [12]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
# [Hint: The size of the array will be 9 and the shape will be (3,3).]


# Create a 3x3 numpy array filled with zeros
zero_array = np.zeros((3, 3))

print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?
# [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]


# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
